.travis.yml, CHANGES.txt, pytesmo/grid/grids.py, pytesmo/grid/netcdf.py, pytesmo/io/ismn/interface.py, pytesmo/io/ismn/metadata_collector.py, pytesmo/io/sat/ascat.py, pytesmo/io/sat/h_saf.py, pytesmo/scaling.py, pytesmo/time_series/__init__.py, pytesmo/timedate/__init__.py, tests/test_dataset_base.py, tests/test_sat/test_h_saf.py
Added python3 support, at least tested functions should work on 2.7, 3.3 and 3.4
=> Python3 support

pytesmo/temporal_matching.py, tests/test_temporal_matching.py
also add tests for temporal matching
=> fix #51 by using NearestNDInterpolator

CHANGES.md, pytesmo/temporal_matching.py, pytesmo/validation_framework/start_validation.py, pytesmo/validation_framework/validation.py, tests/test_temporal_matching.py, tests/test_validation.py
Fix for temporal resampling issue. 
Merge in missing validation framework tests
=> PR for release 0.3.2

pytesmo/time_series/filtering.py, tests/test_time_series/test_filtering.py, tests/test_time_series/test_filters.py
=> Fix moving average with input size 1 and add tests.

CHANGES.md, pytesmo/metrics.py, tests/test_metrics.py
@sebhahn Look it works and was pretty easy.
=> Add Recursive variant of Pearson's R.

.travis.yml, docs/Read_H_SAF_images.rst, pytesmo/io/sat/h_saf.py, requirements.txt, tests/test_grid/test_resample.py, tests/test_sat/test_h_saf.py
=> Refactor H-SAF readers to use pygeobase

pytesmo/io/sat/h_saf.py
=> Return more data from H07 reader.

MANIFEST.in, README.rst, docs/introduction.rst
- Fix #62
- Makes pypi package smaller but excludes test data
- Update installation and developer instructions.
=> Update documentation and exclude docs and test data from package.

CHANGES.md, pytesmo/grid/resample.py, tests/test_grid/test_resample.py
=> Do not change dtype of data during resampling.

pytesmo/io/ismn/interface.py, pytesmo/io/ismn/readers.py, tests/test_ismn/test_readers.py
Now based on reading only the first and last lines of the files and not
parsing the full data.
=> Improve ismn metadata reading of minimum and maximum observation timestamp

pytesmo/validation_framework/validation.py, tests/test_validation_framwork/test_datasets.py, tests/test_validation_framwork/test_validation.py
Can be caused by masking or by temporal matching.
=> Fix empty dataframes in validation

pytesmo/timedate/julian.py, tests/test_timedate/test_julian.py
Related to #103 which I could not yet reproduce.
=> Fix bug in julian microsecond and add tests.

CHANGES.rst, pytesmo/timedate/julian.py, tests/test_timedate/test_julian.py
First step in finding the bug raised by #123
=> Add tests for doy function.

tests/test_validation_framwork/test_validation.py
=> Update test data repository and tests to be compatible with latest ascat

examples/Read_H_SAF_images.py, examples/compare_ISMN_ASCAT.py, examples/plot_ISMN_data.py, examples/read_ASCAT_H25.py, examples/validation_framework.py, pytesmo/validation_framework/start_validation.py
=> Fixing print syntax to be python3 compatible

tests/test_temporal_matching.py
=> Adding unit test for timezone issue

.travis.yml, environment.yml, pytesmo/validation_framework/metric_calculators.py, pytesmo/validation_framework/results_manager.py, pytesmo/validation_framework/validation.py, requirements.txt, tests/test_result_managers.py, tests/test_validation_framwork/test_metric_calculators.py, tests/test_validation_framwork/test_validation.py
It is working, though I'm not entirely happy about the implementation. e.g. pandas doesn't make it easy to use `apply` on multiple columns. I'll try to develop another solution using numba
=> Add rolling metric calculator for pearson r

src/pytesmo/validation_framework/metric_calculators.py
New min_obs keyword argument for Metrics constructor, set to 100 by default.
=> added min_obs keyword

src/pytesmo/metrics/pairwise_utils.py, tests/test_metrics.py
This implements the BCa and basic bootstrap as alternatives to percentile bootstrap.
=> implemented BCa bootstrap method

environment.yml, src/pytesmo/temporal_matching.py, tests/test_temporal_matching.py
Added function from project package to temporally collocate by taking a mean within a window.
=> temporal collocation by taking mean

setup.cfg
=> remove ismn and ascat dependencies

.github/workflows/ci.yml
* env updated
* getting rid of full_framework decorator
* retrieving slow decorator
* retrieving decorators; clearing pytest filters
=> fixing CI (#253)

src/pytesmo/time_series/anomaly.py, tests/test_time_series/test_anomaly.py
Simple method adaptation to compute a month-based climatology in `anomalies.calc_climatology`
=> Monthly climatology

src/pytesmo/validation_framework/adapters.py
Very small fix necessary for https://github.com/awst-austria/qa4sm/pull/520
=> Fixed bug with time unit in basetime

src/pytesmo/time_series/anomaly.py, tests/test_time_series/test_anomaly.py
Fixes for https://github.com/TUW-GEO/pytesmo/issues/264
=> Improved calc_climatology documentation

CHANGELOG.rst, environment.yml, setup.cfg, tests/test_validation_framework/test_adapters.py
=> Remove read_ts from tests, update dependencies accordingly
