- pytesmo/validation_framework/data_manager.py
Updating the string concatenation helps to avoid problems if args are e.g. one element lists or tuples. The old formatting would through an exception in these cases.
> Fix string concatenation for data manager

- pytesmo/validation_framework/data_manager.py
- tests/test_validation.py
This is the default behavior of netCDF4 and we want to catch these
Errors, other RuntimeErrors are still raised.
Fix #88
> Catch RuntimeError in validation framework if file does not exist.

- pytesmo/io/sat/ascat.py
fix #93.
The segfault is not reliably reproduced so we can not write a test for
it but this change fixed it on the setup where it was first discovered.
> Close netCDF file after each reading if read_bulk is not set.

- .travis.yml
- CHANGES.md
- appveyor.yml
- docs/introduction.rst
- pytesmo/scaling.py
- requirements.txt
- tests/test_scaling.py
- tests/test_validation.py
CDF matching is now based on one basic function that performs either
linear CDF matching or interpolates a spline of 5th order.
in_data and scale_to were renamed to src and ref
the statsmodels dependency is no longer needed.
> Refactor scaling

- pytesmo/io/ismn/interface.py
- tests/test_ismn/test_interface.py
This enables nearest neighbor search again.
> ISMN: Replace single kdtree by pygeogrids.BasicGrid.

- .travis.yml
- CHANGES.md
- pytesmo/timedate/julian.py
- tests/test_ismn/test_interface.py
- tests/test_time_series/test_plotting.py
- tests/test_timedate/test_julian.py
It could happen that microseconds where negative in some edge cases.
This commit also fixed the code for the fact that .clip does not work
inplace.
> Fix julian2datetime bug.

- CHANGES.md
- docs/validation_framework.ipynb
- docs/validation_framework.rst
- pytesmo/io/sat/ers.py
- pytesmo/temporal_matching.py
- pytesmo/validation_framework/data_manager.py
- pytesmo/validation_framework/temporal_matchers.py
- pytesmo/validation_framework/validation.py
- tests/test_sat/test_ers.py
- tests/test_validation_framwork/test_validation.py
- Base ERS reader on latest ASCAT package use H-SAF static layers.
- Validation framework can now deal with columns that contain a lot of NaN values but are of no interest during the validation by only dropping NaN values when the columns of interest are already selected.
> Adapt ERS readers and validation framework to latest ascat package version

- CHANGES.rst
- pytesmo/scaling.py
- tests/test_scaling.py
In this implementation, when there are nans in the src or ref series, these lines are removed from the data frame (pandas dropna) (as stats.linreg needs arrays of equal lengths), when the correction params are found (slope, inter) they are applied back to the full array (until now stats.linreg raised an error). Bias correction will probably be worse if there are a lot if nans, but the function should not fail anymore.
@cpaulik : You think this is ok?
> Linear regression scaling with nans

- pytesmo/validation_framework/temporal_matchers.py
- pytesmo/validation_framework/validation.py
This is my attempt at fixing #136 
These two one-line-changes make the unit tests pass. WARNING: However, I'm not sure if I completely understand what the code is doing and what changed.
My understanding is that the problems come from two errors at two places in the code:
pytesmo/validation_framework/temporal_matchers.py:70
E   KeyError: "[('index', '')] not found in axis"
and
pytesmo/validation_framework/validation.py:270
E   AttributeError: 'Index' object has no attribute 'droplevel'
I guess they occur because Pandas changed the way it creates column names. In the matcher case, the column name is ('index', '') with pandas 0.22 and just 'index' with pandas 0.23. In the validation case, pandas 0.22 produces a MultiIndex while pandas 0.23 produces a simple Index with tuples as column …
> Try fixing failing issues with new pandas version (0.23)

- docs/validation_framework.ipynb
- docs/validation_framework.rst
- examples/validation_framework.py
- pytesmo/validation_framework/adapters.py
- tests/test_validation_framwork/test_adapters.py
Extends the existing MaskingAdapter so that it can be used reduce multi-column masking datasets to one column and do "not equal" comparisons. Adds a SelfMaskingAdapter that wraps a data reader and allows to mask the data while reading, based on a comparison operation on one column (column, operation, and threshold can be specified).
> Add masking helpers to validation framework

- CHANGES.rst
- pytesmo/metrics.py
Set the names for metrics input data to general names (`x` and `y` instead of `o` and `p`), so the bias function can not be misinterpreted anymore.
> Change argument names for metrics functions

- docs/introduction.rst
activate `pytesmo` env instead of `test`
> typo fix: conda

- .travis.yml
- appveyor.yml
Update CI a bit.
Dropped Python 3.5 testing and added 3.7. 
For Windows build I had to drop older 32 bit versions since the conda packages of the necessary netcdf4 version do not exist. But I'm not sure if anybody is actually using a 32 bit system.
> Add Python 3.7 and remove 3.5 from CI

- .travis.yml
- appveyor.yml
- pytesmo/timedate/julian.py
- tests/test_timedate/test_julian.py
Had to change a small think in julian date conversion. Since values where returned as arrays when a single float value was the input
> CI: Include builds for Python 3.8

- README.rst
I guess this was not clear at all and thus not done for the last release. 
I've fixed it for `v0.7.1` but with this it is also documented somewhat.
> Add windows release instructions to readme file

- pytesmo/validation_framework/adapters.py
- tests/test_validation_framwork/test_adapters.py
This PR adds an AdvancedMaskingAdapter that can be used to mask the data from a reader based on a list of filters. The list must contain 3-tuples of filter parameter: data column to filter on, operator to use and threshold to use. Operator can either be taken from a pre-defined list (same as in MaskingAdapter) or be a user-defined callable.
We'd like to use it in QA4SM to implement complex masking for SMOS data and think that it'll be useful in pytesmo in general.
Example of SMOS filter:
filtered_reader = AdvancedMaskingAdapter(reader, [
('Scene_Flags', smos_exclude_bitmask, 0b00001000), 
('Soil_Temperature_Level1', '>=', 273), ])        
(where `smos_exclude_bitmask` is a user-defined function)
> Adding AdvancedMaskingAdapter and test

- src/pytesmo/validation_framework/data_manager.py
- src/pytesmo/validation_framework/temporal_matchers.py
- src/pytesmo/validation_framework/validation.py
- tests/test_validation_framwork/test_data_manager.py
- tests/test_validation_framwork/test_validation.py
This changes the behavior of the validation framework.
Before this a validation run with `(n, k)` where `k < n` only gave results for
combinations of datasets which included the temporal reference.
e.g. If 3 dataset (DS1, DS2 and DS3) where given and a metric calculator was run
with `(3, 2)` with the temporal reference DS1. Then only the combinations of
`DS1 - DS2` and `DS1 - DS3` gave results.
This rectifies this behavior to also return results for the combination `DS2 -
DS3` in the above example.
Tests still need to be adapted but I want to discuss this first to see if this
is what people expect.
There are also some edge cases. e.g. If 4 datasets are given but the
configuration of the metric calculator would be `(3, 2)`. I think we should
raise an error in these cases because that would …
> Val Framework compares dataset matches that do not include the temporal reference

- .gitignore
- CHANGELOG.rst
- src/pytesmo/df_metrics.py
- src/pytesmo/metrics.py
- src/pytesmo/time_series/anomaly.py
- src/pytesmo/utils.py
- src/pytesmo/validation_framework/metric_calculators.py
- tests/test_df_metrics.py
- Include more combinations in validation framework, raise error if n < n_datasets
- `n_wise_apply` now can handle (drop) nans in a passed data frame correctly.
- TC metrics calculator has now option to calculate metrics for reference
- Fix deprecation warnings in anomaly adapter (Issue #198)
> Updates for qa4sm and ISMN paper

- README.rst
- docs/examples/temporal_collocation.ipynb
- environment.yml
- src/pytesmo/temporal_matching.py
- tests/test_temporal_matching.py
This contains a new implementation of temporal matching/collocation, as discussed in #176.
It uses ``pd.reindex`` for matching with nearest neighbours, as was done in `smecv`. I added a method keyword, so different collocation/interpolation methods can be implemented in the future, if necessary.
> New temporal matching/collocation implementation

- src/pytesmo/scaling.py
- src/pytesmo/utils.py
- tests/test_scaling.py
- tests/test_utils.py
This PR provides an update on the CDF scaling methods in `scaling.py` based on Moesinger et al. (2020). It includes:
- The function `cdf_beta_match`, allowing to scale the source to the reference timeseries using the CDF of the reference and the CDF of the source, fitted on a beta distribution function
- An improved methodology for the scaling of values below the second and above the penultimate percentiles
- An improved methodology to dynamically increase the size of percentile bins in case too few observations are found in a bin, avoiding issues with the overfitting of scaling parameters
The improvements have been made available for the `cdf_match` and `lin_cdf_match` functions as well, although all changes are optional to avoid issues with previous uses of Pytesmo.
> Cdf matching issue 309

- src/pytesmo/time_series/anomaly.py
- tests/test_time_series/test_anomaly.py
If input data is less than 1 year then this failed because it tried to index
days that did not exist
> Fix bug in indexing when interpolate leapday was set

- tests/test_metrics_deprecated.py
This failed for on a machine (osx arm64) with
```
def test_mse(arange_testdata):
"""
Test for mse
"""
with pytest.deprecated_call():
x, y = arange_testdata
mse_pred = 4.
mse_bias_pred = 2. ** 2
mse_obs, _, mse_bias, _ = met.mse(x, y)
>           nptest.assert_equal(mse_obs, mse_pred)
E           AssertionError:
E           Items are not equal:
E            ACTUAL: 4.0000000000000036
E            DESIRED: 4.0
```
> Use assert_almost_equal in deprecated MSE test

- src/pytesmo/validation_framework/adapters.py
- tests/test_validation_framework/test_adapters.py
Recently I had the case where we had multiple layers of RZSM in a dataset and wanted to compare it to a model which had one (much wider) layer as the reference. So I wrote this adapter to merge columns upon passing them into the validation framework. What do you think @s-scherrer @pstradio does this make sense here?
> Add adapter to combine multiple columns returned by read function

- src/pytesmo/metrics/_fast_pairwise.pyx
- src/pytesmo/validation_framework/metric_calculators.py
Some readers return data not as float64 (but as float32) in that case the rollmetrics may not get data in the expected format. This forces float64 to fix this.
> Fix rollmetric

- .gitignore
- LICENSE.txt
- docs/examples/validation_framework.ipynb
- src/pytesmo/colormaps/load_cmap.py
- src/pytesmo/df_metrics.py
- src/pytesmo/metrics/_fast.c
- src/pytesmo/metrics/_fast_pairwise.c
- src/pytesmo/metrics/_fast_pairwise.pyx
- src/pytesmo/metrics/deprecated.py
- src/pytesmo/scaling.py
- src/pytesmo/time_series/filters.c
- src/pytesmo/timedate/julian.py
- src/pytesmo/utils.py
- src/pytesmo/validation_framework/adapters.py
- src/pytesmo/validation_framework/data_manager.py
- src/pytesmo/validation_framework/data_scalers.py
- src/pytesmo/validation_framework/metric_calculators.py
- src/pytesmo/validation_framework/results_manager.py
- src/pytesmo/validation_framework/temporal_matchers.py
- src/pytesmo/validation_framework/upscaling.py
- src/pytesmo/validation_framework/validation.py
- tests/test_validation_framework/test_adapters.py
- tests/test_validation_framework/test_datasets.py
- tests/test_validation_framework/test_metric_calculators.py
- tests/test_validation_framework/test_validation.py
Most changes here (also in C files) are due to applying pre-commit hooks.
The 2 relevant parts are
- In src/pytesmo/validation_framework/adapters.py I added a keyword that allows adding a method other than ``read``/``read_ts`` to the adapters. Data from this method (which is expected to return a DataFrame) is modified in the same way as for read/read_ts. By default, nothing changes compared to the previous implementation.
- In some places I replaced the default `read_ts` function with `read`, as ``read_ts`` is [deprecated in pygeobase](https://github.com/TUW-GEO/pygeobase/blob/master/src/pygeobase/io_base.py#L689) and leads to many warnings when used in the validation framework.
> Add option for custom reading method name to adapters

- src/pytesmo/validation_framework/metric_calculators.py
- src/pytesmo/validation_framework/validation.py
Handles exceptions in `validation_framework.validation.calc()` when a metric is not computed (e.g. TC errors) and not written to the results dictionary.
> Calc debugging

- CHANGELOG.rst
- src/pytesmo/validation_framework/adapters.py
- tests/test_validation_framework/test_adapters.py
Added a timestamp adapter for datasets that are read with an index in midnight UTC units and an additional field with the time offset. The adapter returns the original fields with the exact observation timestamp.
Applicable for instance to:
- SMOS L3
- SMAP L3
- C3S
- CCI
> Added timestamp adapter

- environment.yml
- src/pytesmo/validation_framework/adapters.py
- tests/test_validation_framework/test_adapters.py
Method for masking to ignore NaNs in filter columns, i.e. observations can be kept if no information is given by the filtering field.
> Ignore nans masking

- src/pytesmo/validation_framework/data_manager.py
- src/pytesmo/validation_framework/validation.py
- tests/test_validation_framework/test_data_manager.py
- tests/test_validation_framework/test_metric_calculators.py
- tests/test_validation_framework/utils.py
Since pygeobase does not support max_dist in `_read_latlon` yet, I implemented the gpi finding here manually. I had to adapt the tests slightly to make it work.
I will still need to add a test for the behaviour.
> respect max_dist in validation

- src/pytesmo/validation_framework/metric_calculators_adapters.py
Bugfix the SubsetsMetricsAdapter to prevent missing grid points for validation with triple collocation together with stability or intra-annual metrics
> Bugfix SubsetsMetricsAdapter #313
